// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type FileChunkMessage struct {
	ID               int64
	FilesToSyncFk    int64
	ChunkNumber      int32
	DiscordMessageID string
}

type FilesToSync struct {
	FileToSyncUri           string
	DiscordGuildSnowflake   string
	DiscordChannelSnowflake string
	ID                      int64
	FileContents            string
}

type GithubRepoFile struct {
	ID            int64
	GithubRepoUrl string
	FileToSyncFk  int64
}

type SchemaMigration struct {
	Version string
}
